import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db';
import bcrypt from 'bcryptjs';

// One-time seed route — DELETE THIS FILE after seeding
export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const secret = searchParams.get('secret');

  if (secret !== process.env.NEXTAUTH_SECRET) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const hashedPassword = await bcrypt.hash('johndoe123', 10);
    await prisma.user.upsert({
      where: { email: 'john@doe.com' },
      update: {},
      create: { email: 'john@doe.com', password: hashedPassword, name: 'Test Parent' },
    });

    await prisma.activity.deleteMany({});

    const activities = [
      // Breathing
      { title: 'Belly Breathing', description: 'Put your hands on your tummy and breathe slowly', type: 'breathing', category: 'calm', imageUrl: null, content: JSON.stringify({ instruction: 'Put your hands on your tummy. Feel it go up and down as you breathe!', cycles: 3, phases: [{ label: 'Breathe In', duration: 4, color: '#60B5FF', expand: true }, { label: 'Breathe Out', duration: 4, color: '#80D8C3', expand: false }] }), difficulty: 1, starsReward: 2 },
      { title: 'Box Breathing', description: 'Breathe in, hold, breathe out, hold — like drawing a box!', type: 'breathing', category: 'calm', imageUrl: null, content: JSON.stringify({ instruction: 'Follow the circle to breathe like a box — 4 sides, 4 counts each.', cycles: 3, phases: [{ label: 'Breathe In', duration: 4, color: '#60B5FF', expand: true }, { label: 'Hold', duration: 4, color: '#BB8FCE', expand: true }, { label: 'Breathe Out', duration: 4, color: '#80D8C3', expand: false }, { label: 'Hold', duration: 4, color: '#FF9149', expand: false }] }), difficulty: 2, starsReward: 2 },
      { title: 'Star Breathing', description: 'Breathe in and out 5 times — one for each star point!', type: 'breathing', category: 'calm', imageUrl: null, content: JSON.stringify({ instruction: 'Imagine a star! Each breath takes you to a new point on the star.', cycles: 5, phases: [{ label: 'Breathe In', duration: 3, color: '#FFD700', expand: true }, { label: 'Breathe Out', duration: 3, color: '#FF9149', expand: false }] }), difficulty: 1, starsReward: 2 },
      // Emotions
      { title: 'Find Happy!', description: 'Can you find the happy face?', type: 'emotion', category: 'happy', imageUrl: 'https://cdn.abacus.ai/images/a787547d-75e2-491e-9a32-79f6a6f8b545.jpg', content: JSON.stringify({ emotion: 'happy' }), difficulty: 1, starsReward: 1 },
      { title: 'Find Sad!', description: 'Can you find the sad face?', type: 'emotion', category: 'sad', imageUrl: 'https://cdn.abacus.ai/images/449d23ac-d94d-4502-8095-e1d985ecb1bd.jpg', content: JSON.stringify({ emotion: 'sad' }), difficulty: 1, starsReward: 1 },
      { title: 'Find Surprised!', description: 'Can you find the surprised face?', type: 'emotion', category: 'surprised', imageUrl: 'https://cdn.abacus.ai/images/a2b11f46-14b4-4860-b8f7-fcd4f5f2d8ef.jpg', content: JSON.stringify({ emotion: 'surprised' }), difficulty: 1, starsReward: 1 },
      { title: 'Find Excited!', description: 'Can you find the excited face?', type: 'emotion', category: 'excited', imageUrl: 'https://cdn.abacus.ai/images/1a31838e-02cd-4676-b8d7-0fdec237e3db.jpg', content: JSON.stringify({ emotion: 'excited' }), difficulty: 2, starsReward: 1 },
      { title: 'Find Angry!', description: 'Can you find the angry face?', type: 'emotion', category: 'angry', imageUrl: 'https://cdn.abacus.ai/images/9924338c-9cb3-482e-bf9e-de1970eef82d.jpg', content: JSON.stringify({ emotion: 'angry' }), difficulty: 2, starsReward: 1 },
      { title: 'Find Scared!', description: 'Can you find the scared face?', type: 'emotion', category: 'scared', imageUrl: 'https://cdn.abacus.ai/images/b0785242-a22c-4999-950c-4845cddfca02.jpg', content: JSON.stringify({ emotion: 'scared' }), difficulty: 2, starsReward: 1 },
      // Scenarios
      { title: 'Saying Hello', description: 'You see a friend at the playground. What should you do?', type: 'scenario', category: 'greeting', imageUrl: 'https://cdn.abacus.ai/images/a694cc55-9041-4e3a-b6f1-8b18cb56ef73.jpg', content: JSON.stringify({ scenario: 'greeting', choices: [{ text: 'Wave and say "Hi!"', isCorrect: true, feedback: 'That\'s a friendly way to greet someone!' }, { text: 'Turn away and ignore them', isCorrect: false, feedback: 'It\'s nice to say hello to friends.' }, { text: 'Run away', isCorrect: false, feedback: 'Try waving and saying hi instead!' }] }), difficulty: 1, starsReward: 2 },
      { title: 'Sharing Toys', description: 'Your friend wants to play with your toy. What should you do?', type: 'scenario', category: 'sharing', imageUrl: 'https://cdn.abacus.ai/images/ce62a709-3173-4af2-bb1d-966a5b6cabb8.jpg', content: JSON.stringify({ scenario: 'sharing', choices: [{ text: 'Share and take turns', isCorrect: true, feedback: 'Great! Sharing makes everyone happy!' }, { text: 'Say "No! It\'s mine!"', isCorrect: false, feedback: 'Sharing helps us make friends.' }, { text: 'Take all the toys away', isCorrect: false, feedback: 'Let\'s try sharing instead!' }] }), difficulty: 2, starsReward: 2 },
      { title: 'Helping a Friend', description: 'Your friend dropped their crayons. What should you do?', type: 'scenario', category: 'helping', imageUrl: 'https://cdn.abacus.ai/images/cb0f72ba-d55f-4e82-b34b-2d99c229def4.jpg', content: JSON.stringify({ scenario: 'helping', choices: [{ text: 'Help them pick up the crayons', isCorrect: true, feedback: 'You\'re so helpful! That\'s very kind!' }, { text: 'Walk away', isCorrect: false, feedback: 'It feels good to help others.' }, { text: 'Laugh at them', isCorrect: false, feedback: 'Let\'s be kind and help instead!' }] }), difficulty: 2, starsReward: 2 },
      { title: 'Taking Turns', description: 'Everyone wants to go on the slide. What should you do?', type: 'scenario', category: 'takingTurns', imageUrl: 'https://cdn.abacus.ai/images/97cca0a3-bcab-4e6c-b861-9585254062db.jpg', content: JSON.stringify({ scenario: 'takingTurns', choices: [{ text: 'Wait in line and take turns', isCorrect: true, feedback: 'Perfect! Taking turns makes playtime fun for everyone!' }, { text: 'Push in front of everyone', isCorrect: false, feedback: 'We need to take turns so everyone can have fun.' }, { text: 'Leave the playground', isCorrect: false, feedback: 'Just wait your turn — you\'ll get to play soon!' }] }), difficulty: 2, starsReward: 2 },
      { title: 'Asking for Help', description: 'You can\'t open your lunchbox. What should you do?', type: 'scenario', category: 'askingHelp', imageUrl: 'https://cdn.abacus.ai/images/cb0f72ba-d55f-4e82-b34b-2d99c229def4.jpg', content: JSON.stringify({ scenario: 'askingHelp', choices: [{ text: 'Ask a teacher or friend for help', isCorrect: true, feedback: 'Asking for help is a brave and smart thing to do!' }, { text: 'Cry and give up', isCorrect: false, feedback: 'It\'s OK to ask someone for help!' }, { text: 'Throw the lunchbox', isCorrect: false, feedback: 'Let\'s try asking for help instead.' }] }), difficulty: 1, starsReward: 2 },
      { title: 'When I Make a Mistake', description: 'You spilled paint on your friend\'s drawing by accident. What do you do?', type: 'scenario', category: 'mistakes', imageUrl: 'https://cdn.abacus.ai/images/53dce2b0-a6e3-4893-bb9f-872909ee336c.jpg', content: JSON.stringify({ scenario: 'mistakes', choices: [{ text: 'Say "I\'m sorry" and help clean it up', isCorrect: true, feedback: 'Saying sorry and helping is the kind thing to do!' }, { text: 'Run away and pretend it didn\'t happen', isCorrect: false, feedback: 'It\'s always better to say sorry.' }, { text: 'Blame someone else', isCorrect: false, feedback: 'Telling the truth and saying sorry is brave!' }] }), difficulty: 2, starsReward: 2 },
      { title: 'Feeling Angry', description: 'You feel very angry because someone took your toy. What is the best thing to do?', type: 'scenario', category: 'emotionRegulation', imageUrl: 'https://cdn.abacus.ai/images/9924338c-9cb3-482e-bf9e-de1970eef82d.jpg', content: JSON.stringify({ scenario: 'emotionRegulation', choices: [{ text: 'Take three deep breaths and use words to say how I feel', isCorrect: true, feedback: 'Taking deep breaths is a superpower when we feel angry!' }, { text: 'Hit the person', isCorrect: false, feedback: 'We never hurt others. Try breathing and using words instead.' }, { text: 'Scream and throw things', isCorrect: false, feedback: 'Let\'s try breathing slowly to calm our body.' }] }), difficulty: 2, starsReward: 2 },
      { title: 'Joining a Group', description: 'Some kids are playing a game. You want to join them. What do you do?', type: 'scenario', category: 'joining', imageUrl: 'https://cdn.abacus.ai/images/a694cc55-9041-4e3a-b6f1-8b18cb56ef73.jpg', content: JSON.stringify({ scenario: 'joining', choices: [{ text: 'Walk over and ask "Can I play too?"', isCorrect: true, feedback: 'Asking politely is the perfect way to join in!' }, { text: 'Push into the game without asking', isCorrect: false, feedback: 'It\'s polite to ask first before joining.' }, { text: 'Stand far away and watch quietly', isCorrect: false, feedback: 'You can do it — walk over and ask to join!' }] }), difficulty: 2, starsReward: 2 },
      // Stories
      { title: 'The Playground Friends', description: 'A story about making new friends', type: 'story', category: 'playground', imageUrl: 'https://cdn.abacus.ai/images/83e2b54b-1e7d-40a7-a853-188cac3c99d8.jpg', content: JSON.stringify({ pages: [{ text: 'Lily went to the playground. She saw other children playing.', image: 'https://cdn.abacus.ai/images/83e2b54b-1e7d-40a7-a853-188cac3c99d8.jpg' }, { text: 'Lily wanted to play too. She walked over and smiled at them.', image: 'https://cdn.abacus.ai/images/a694cc55-9041-4e3a-b6f1-8b18cb56ef73.jpg', question: 'What did Lily do?', options: ['She smiled and said hi', 'She ran away', 'She cried'], correctAnswer: 0 }, { text: '"Hi! Can I play with you?" Lily asked. The children said "Yes! Come play!"', image: 'https://cdn.abacus.ai/images/ce62a709-3173-4af2-bb1d-966a5b6cabb8.jpg' }, { text: 'They all played together and had so much fun! Lily made new friends.', image: 'https://cdn.abacus.ai/images/97cca0a3-bcab-4e6c-b861-9585254062db.jpg' }] }), difficulty: 2, starsReward: 3 },
      { title: 'Circle Time at School', description: 'Learning to listen and share', type: 'story', category: 'classroom', imageUrl: 'https://cdn.abacus.ai/images/53dce2b0-a6e3-4893-bb9f-872909ee336c.jpg', content: JSON.stringify({ pages: [{ text: 'It was circle time at school. Everyone sat together on the colorful rug.', image: 'https://cdn.abacus.ai/images/53dce2b0-a6e3-4893-bb9f-872909ee336c.jpg' }, { text: 'The teacher asked, "Who wants to share their weekend story?" Many hands went up!', image: 'https://cdn.abacus.ai/images/53dce2b0-a6e3-4893-bb9f-872909ee336c.jpg', question: 'What should you do when you want to talk?', options: ['Raise your hand', 'Shout loudly', 'Talk over others'], correctAnswer: 0 }, { text: 'Sam raised his hand and waited. The teacher called on him. Sam felt proud!', image: 'https://cdn.abacus.ai/images/53dce2b0-a6e3-4893-bb9f-872909ee336c.jpg' }, { text: 'Everyone listened to Sam\'s story. Then it was someone else\'s turn. Taking turns is important!', image: 'https://cdn.abacus.ai/images/53dce2b0-a6e3-4893-bb9f-872909ee336c.jpg' }] }), difficulty: 2, starsReward: 3 },
      { title: 'The Dragon Who Felt Angry', description: 'A story about handling big feelings', type: 'story', category: 'angermanagement', imageUrl: 'https://cdn.abacus.ai/images/9924338c-9cb3-482e-bf9e-de1970eef82d.jpg', content: JSON.stringify({ pages: [{ text: 'Dex the dragon had big, fiery feelings inside. When things went wrong, he felt very angry.', image: 'https://cdn.abacus.ai/images/9924338c-9cb3-482e-bf9e-de1970eef82d.jpg' }, { text: 'One day, another dragon accidentally knocked over Dex\'s blocks. Dex felt his anger growing!', image: 'https://cdn.abacus.ai/images/9924338c-9cb3-482e-bf9e-de1970eef82d.jpg' }, { text: 'Dex remembered what he learned. He took a big, slow breath in... and let it out slowly.', image: 'https://cdn.abacus.ai/images/9924338c-9cb3-482e-bf9e-de1970eef82d.jpg', question: 'What did Dex do to calm down?', options: ['Took a deep breath', 'Roared fire at everyone', 'Ran away'], correctAnswer: 0 }, { text: '"I feel angry that you knocked my blocks," Dex said calmly. "Let\'s build them together." Problem solved!', image: 'https://cdn.abacus.ai/images/a694cc55-9041-4e3a-b6f1-8b18cb56ef73.jpg' }] }), difficulty: 3, starsReward: 3 },
      { title: 'When I Feel Worried', description: 'A story about dealing with worry', type: 'story', category: 'anxiety', imageUrl: 'https://cdn.abacus.ai/images/b0785242-a22c-4999-950c-4845cddfca02.jpg', content: JSON.stringify({ pages: [{ text: 'Mia had butterflies in her tummy. She was starting a new school today and felt very worried.', image: 'https://cdn.abacus.ai/images/b0785242-a22c-4999-950c-4845cddfca02.jpg' }, { text: 'Mia\'s mum held her hand. "It\'s okay to feel worried," she said. "What helps when you feel this way?"', image: 'https://cdn.abacus.ai/images/b0785242-a22c-4999-950c-4845cddfca02.jpg', question: 'What can help when you feel worried?', options: ['Take deep breaths and talk to someone', 'Hide under the bed', 'Eat lots of sweets'], correctAnswer: 0 }, { text: 'Mia took three slow deep breaths. She thought of her favourite toy at home waiting for her.', image: 'https://cdn.abacus.ai/images/991e7112-f748-4224-95f5-287204544337.jpg' }, { text: 'At school, the teacher was kind and Mia found a friend by lunchtime. Worry can shrink when we breathe and try!', image: 'https://cdn.abacus.ai/images/a694cc55-9041-4e3a-b6f1-8b18cb56ef73.jpg' }] }), difficulty: 2, starsReward: 3 },
      // Communication
      { title: 'How I Feel', description: 'Practice saying how you feel using pictures', type: 'communication', category: 'feelings', imageUrl: null, content: JSON.stringify({ instruction: 'Tap a picture to say how you feel! Tap 5 feelings.', targetTaps: 5, items: [{ label: 'Happy', emoji: '😊', audio: 'I feel happy!' }, { label: 'Sad', emoji: '😢', audio: 'I feel sad.' }, { label: 'Angry', emoji: '😠', audio: 'I feel angry.' }, { label: 'Scared', emoji: '😨', audio: 'I feel scared.' }, { label: 'Excited', emoji: '🤩', audio: 'I feel excited!' }, { label: 'Calm', emoji: '😌', audio: 'I feel calm.' }, { label: 'Tired', emoji: '😴', audio: 'I feel tired.' }, { label: 'Silly', emoji: '😜', audio: 'I feel silly!' }, { label: 'Worried', emoji: '😟', audio: 'I feel worried.' }, { label: 'Loved', emoji: '🥰', audio: 'I feel loved!' }, { label: 'Frustrated', emoji: '😤', audio: 'I feel frustrated.' }, { label: 'Surprised', emoji: '😲', audio: 'I feel surprised!' }] }), difficulty: 1, starsReward: 2 },
      { title: 'What I Need', description: 'Practice asking for what you need', type: 'communication', category: 'needs', imageUrl: null, content: JSON.stringify({ instruction: 'Tap a picture to say what you need! Tap 5 things.', targetTaps: 5, items: [{ label: 'Water', emoji: '💧', audio: 'I need water please.' }, { label: 'Food', emoji: '🍎', audio: 'I am hungry.' }, { label: 'Bathroom', emoji: '🚽', audio: 'I need the bathroom please.' }, { label: 'A Hug', emoji: '🤗', audio: 'I need a hug please.' }, { label: 'Quiet', emoji: '🤫', audio: 'It is too loud. I need quiet please.' }, { label: 'Help', emoji: '🙋', audio: 'I need help please.' }, { label: 'A Break', emoji: '⏸️', audio: 'I need a break please.' }, { label: 'Music', emoji: '🎵', audio: 'I want to listen to music please.' }, { label: 'My Toy', emoji: '🧸', audio: 'I want my comfort toy please.' }, { label: 'Outside', emoji: '🌳', audio: 'I want to go outside please.' }, { label: 'Sleep', emoji: '😴', audio: 'I am sleepy and need to rest.' }, { label: 'A Story', emoji: '📖', audio: 'Can you read me a story please?' }] }), difficulty: 1, starsReward: 2 },
      { title: "Let's Say Hello!", description: 'Practice greetings and conversation starters', type: 'communication', category: 'greetings', imageUrl: null, content: JSON.stringify({ instruction: 'Tap a picture to practise talking to others! Tap 4 greetings.', targetTaps: 4, items: [{ label: 'Hello!', emoji: '👋', audio: 'Hello!' }, { label: 'Good Morning', emoji: '🌅', audio: 'Good morning!' }, { label: 'How are you?', emoji: '💬', audio: 'How are you?' }, { label: 'My name is...', emoji: '🏷️', audio: 'My name is...' }, { label: 'Can I play?', emoji: '🎮', audio: 'Can I play with you?' }, { label: 'Thank You', emoji: '🙏', audio: 'Thank you!' }, { label: 'Please', emoji: '😊', audio: 'Please.' }, { label: 'Goodbye', emoji: '👋', audio: 'Goodbye! See you later!' }, { label: 'I like you', emoji: '❤️', audio: 'I like you!' }, { label: "Let's play!", emoji: '🤝', audio: "Let's play together!" }, { label: 'Wait please', emoji: '✋', audio: 'Wait please.' }, { label: 'Yes', emoji: '✅', audio: 'Yes!' }] }), difficulty: 1, starsReward: 2 },
    ];

    for (const activity of activities) {
      await prisma.activity.create({ data: activity as any });
    }

    return NextResponse.json({ success: true, activities: activities.length });
  } catch (error) {
    console.error('Seed error:', error);
    return NextResponse.json({ error: String(error) }, { status: 500 });
  }
}
